services:
  mini-qr:
    image: ghcr.io/lyqht/mini-qr:latest
    container_name: mini-qr
    restart: unless-stopped

  qr-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: qr-api
    restart: unless-stopped
    depends_on:
      - mini-qr
